-- Supabase SQL Migration: 01_resources.sql
-- Create resources table for IB Vault
CREATE TABLE IF NOT EXISTS public.resources (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  cost TEXT NOT NULL CHECK (cost IN ('Free', 'Freemium')),
  rank INTEGER NOT NULL DEFAULT 3 CHECK (rank BETWEEN 1 AND 5),
  is_new BOOLEAN NOT NULL DEFAULT false,
  added_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'pending', 'broken')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read for approved resources
CREATE POLICY "Allow public read approved" ON public.resources
  FOR SELECT USING (status = 'approved');

-- Allow anonymous submission with pending status
CREATE POLICY "Allow public insert pending" ON public.resources
  FOR INSERT WITH CHECK (status = 'pending');

-- Allow admin full access
CREATE POLICY "Allow full admin access" ON public.resources
  FOR ALL USING (auth.role() = 'authenticated');

-- Allow anonymous status updates (approve/broken toggle)
CREATE POLICY "Allow public update status" ON public.resources
  FOR UPDATE USING (true) WITH CHECK (status IN ('approved', 'broken'));

-- Seed data insertion
INSERT INTO public.resources (id, name, url, description, category, cost, rank, is_new, added_date, status) VALUES
  ('pirateib-master-hubs-repositories', 'pirateIB', 'https://pirateib.sh', 'Community hub linking to past papers, textbooks, question banks, exemplars', 'Master Hubs & Repositories', 'Free', 5, FALSE, '2025-09-09', 'approved'),
  ('pirateib-repository-master-hubs-repositories', 'pirateIB Repository', 'https://dl.pirateib.sh', 'File-browser access to the full repo', 'Master Hubs & Repositories', 'Free', 5, FALSE, '2025-09-21', 'approved'),
  ('pirateib-repo-zips-master-hubs-repositories', 'pirateIB Repo ZIPs', 'https://dl.pirateib.sh/DOWNLOAD%20REPO%20-%20ZIPS/', 'Downloadable ZIP archives of the whole repo', 'Master Hubs & Repositories', 'Free', 5, FALSE, '2025-09-14', 'approved'),
  ('pirateib-legacy-mirror-master-hubs-repositories', 'pirateIB legacy mirror', 'https://pirateib.xyz', 'Alternate/backup mirror domain', 'Master Hubs & Repositories', 'Free', 3, FALSE, '2025-09-26', 'approved'),
  ('repo-pirateib-net-master-hubs-repositories', 'repo.pirateib.net', 'https://repo.pirateib.net', 'Legacy textbook/workbook/answer-book repo', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-20', 'approved'),
  ('pirateib-resource-guide-master-hubs-repositories', 'pirateIB Resource Guide', 'https://pirateib.sh/resguide/', 'Master index of all pirateIB resources', 'Master Hubs & Repositories', 'Free', 5, FALSE, '2025-09-11', 'approved'),
  ('ibresources-cc-master-hubs-repositories', 'ibresources.cc', 'https://ibresources.cc', 'Clean categorized directory of IB tools and notes', 'Master Hubs & Repositories', 'Free', 5, FALSE, '2025-09-21', 'approved'),
  ('ibresources-cc-mirror-list-master-hubs-repositories', 'ibresources.cc Mirror List', 'https://ibresources.cc/mirrors2', 'Live-updated list of repo mirrors when domains die', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-09', 'approved'),
  ('ibdocs-re-master-hubs-repositories', 'IBDocs.re', 'https://ibdocs.re', 'Past-paper archive, strong for Maths HL', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-12', 'approved'),
  ('revisiondojo-master-hubs-repositories', 'RevisionDojo', 'https://revisiondojo.com', 'AI notes/question bank plus uni-prep tools', 'Master Hubs & Repositories', 'Freemium', 4, FALSE, '2025-09-22', 'approved'),
  ('village-pirateib-master-hubs-repositories', 'Village (pirateIB)', 'https://village.pirateib.su', 'Community/collaboration space', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-22', 'approved'),
  ('hack-your-course-ib-guide-master-hubs-repositories', 'Hack Your Course IB Guide', 'https://www.hackyourcourse.com/ib-free-resources/', 'Directory of 65+ resources with pros/cons per subject', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-29', 'approved'),
  ('ben-s-maths-ib-guide-master-hubs-repositories', 'Ben''s Maths IB Guide', 'https://papers.bensmaths.com/ib-guide', 'Reviewed comparison of 44+ Maths AA/AI resources', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-26', 'approved'),
  ('concordian-libguides-master-hubs-repositories', 'Concordian Libguides', 'https://concordian-thailand.libguides.com', 'Past papers, study guides, worksheets, IA tips per subject', 'Master Hubs & Repositories', 'Free', 3, FALSE, '2025-09-10', 'approved'),
  ('iblieve-org-master-hubs-repositories', 'iblieve.org', 'https://iblieve.org', 'General IB community/resource site', 'Master Hubs & Repositories', 'Free', 3, FALSE, '2025-09-04', 'approved'),
  ('theib2u-com-master-hubs-repositories', 'theib2u.com', 'https://theib2u.com', 'Video explanations across subjects', 'Master Hubs & Repositories', 'Free', 3, FALSE, '2025-09-08', 'approved'),
  ('studyib-directory-master-hubs-repositories', 'StudyIB Directory', 'https://www.studyib.com/ib/', 'Reviews and links to dozens of IB tools', 'Master Hubs & Repositories', 'Free', 4, FALSE, '2025-09-03', 'approved'),
  ('pirateib-question-banks-past-papers-question-banks', 'pirateIB Question Banks', 'https://dl.pirateib.sh/IB%20QUESTIONBANKS/', 'Topic and paper-sorted question banks, v4-v6', 'Past Papers & Question Banks', 'Free', 5, FALSE, '2025-09-20', 'approved'),
  ('pestle-current-past-papers-question-banks', 'Pestle (current)', 'https://pestle.pages.dev', 'Filterable topic question bank, community standard', 'Past Papers & Question Banks', 'Free', 5, TRUE, '2025-09-26', 'approved'),
  ('pestle-v4-past-papers-question-banks', 'Pestle v4', 'https://pestle-ib.firebaseapp.com', 'Legacy-syllabus topic question bank', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-04', 'approved'),
  ('pestle-v3-past-papers-question-banks', 'Pestle v3', 'https://pestlev3.netlify.app', 'Intermediate backup version', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-25', 'approved'),
  ('savemyexams-archive-past-papers-question-banks', 'SaveMyExams Archive', 'https://smearchive.pages.dev', 'Free mirror of paid SaveMyExams notes/papers', 'Past Papers & Question Banks', 'Free', 5, FALSE, '2025-09-14', 'approved'),
  ('savemyexams-notes-mirror-past-papers-question-banks', 'SaveMyExams Notes mirror', 'https://dl.pirateib.sh/SaveMyExams%20-%20Notes/', 'Direct-download SME revision notes', 'Past Papers & Question Banks', 'Free', 4, FALSE, '2025-09-20', 'approved'),
  ('inthinking-studyib-mirror-past-papers-question-banks', 'InThinking StudyIB mirror', 'https://dl.pirateib.sh/StudyIB/', 'Free copy of paywalled StudyIB teacher content', 'Past Papers & Question Banks', 'Free', 4, FALSE, '2025-09-08', 'approved'),
  ('inthinking-thinkib-mirror-past-papers-question-banks', 'InThinking ThinkIB mirror', 'https://dl.pirateib.sh/ThinkIB/', 'Free copy of paywalled ThinkIB teacher content', 'Past Papers & Question Banks', 'Free', 4, FALSE, '2025-09-17', 'approved'),
  ('revision-town-past-papers-question-banks', 'Revision Town', 'https://revisiontown2024.pages.dev', 'Alternative notes/paper archive', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-06', 'approved'),
  ('igcse-net-past-papers-past-papers-question-banks', 'IGCSE.net Past Papers', 'https://igcse.net/free-ib-past-paper-download-2019-2020/', 'Legacy IB past papers 1999-2018/2020', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-09', 'approved'),
  ('freeexampapers-com-past-papers-question-banks', 'freeexampapers.com', 'https://freeexampapers.com/exam-papers/IB/', 'Legacy paper archive 1999-2017', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-02', 'approved'),
  ('chemistry-legacy-papers-drive-past-papers-question-banks', 'Chemistry legacy papers (Drive)', 'https://drive.google.com/drive/folders/1tI_eujDePcxI60511UNPFFZjU4x0rmc6', 'Chemistry-specific 1999-2018 papers', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-07', 'approved'),
  ('smashingscience-chem-papers-past-papers-question-banks', 'SmashingScience Chem Papers', 'https://www.smashingscience.org/ib-chemistry-hl-sl', 'Chemistry HL/SL paper collection', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-30', 'approved'),
  ('exampaperspractice-maths-aa-hl-past-papers-question-banks', 'ExamPapersPractice Maths AA HL', 'https://www.exampaperspractice.co.uk/ib-maths-aa-hl-topic-questions/', 'Topic-sorted AA HL questions', 'Past Papers & Question Banks', 'Free', 4, FALSE, '2025-09-08', 'approved'),
  ('markscheme-app-past-papers-question-banks', 'MarkScheme.app', 'https://markscheme.app/ib/past-papers/chemistry-hl', 'Legal free past papers and mark schemes', 'Past Papers & Question Banks', 'Free', 4, TRUE, '2025-09-30', 'approved'),
  ('papersdaddy-past-papers-question-banks', 'PapersDaddy', 'https://www.papersdaddy.com/ib/score-calculator', '115,000+ free multi-board past papers', 'Past Papers & Question Banks', 'Free', 3, FALSE, '2025-09-28', 'approved'),
  ('revision-village-free-tier-past-papers-question-banks', 'Revision Village (free tier)', 'https://revisionvillage.com', 'Paid platform''s free sample papers and videos', 'Past Papers & Question Banks', 'Freemium', 4, FALSE, '2025-09-30', 'approved'),
  ('christos-nikolaidis-practice-questions-mathematics-aa-hl', 'Christos Nikolaidis Practice Questions', 'https://www.christosnikolaidis.com/en/maa-exercise/', 'Community-favorite exercise banks, formula booklets, Paper 3 specimens', 'Mathematics AA HL', 'Free', 5, FALSE, '2025-09-02', 'approved'),
  ('maths-notes-drive-folder-mathematics-aa-hl', 'Maths Notes Drive Folder', 'https://drive.google.com/drive/folders/1qcZltzQ1mqebf2ZKNu1hkSIJxwAunYp9', 'Community-shared complete notes folder', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-08', 'approved'),
  ('quester-maths-aa-notes-mathematics-aa-hl', 'Quester Maths AA Notes', 'https://quester.io/q/23787019/maths_aa', 'Structured topic notes', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-07', 'approved'),
  ('quester-aa-hl-paper-3-mathematics-aa-hl', 'Quester AA HL Paper 3', 'https://quester.io/q/66622945/hl_paper_3', 'Paper 3 investigation-style practice', 'Mathematics AA HL', 'Free', 4, TRUE, '2025-09-30', 'approved'),
  ('addvance-maths-mathematics-aa-hl', 'Addvance Maths', 'https://addvancemaths.com/ibaasl/', 'Full revision site with companion YouTube channel', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('examsolutions-mathematics-aa-hl', 'ExamSolutions', 'https://www.examsolutions.net/international-exams/international-baccalaureate/', 'Concept videos mapped to IB Maths topics', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-08', 'approved'),
  ('znotes-mathematics-mathematics-aa-hl', 'ZNotes Mathematics', 'https://znotes.org', 'Community summary notes, all 4 Maths routes', 'Mathematics AA HL', 'Freemium', 4, FALSE, '2025-09-12', 'approved'),
  ('blitznotes-maths-aa-mathematics-aa-hl', 'BlitzNotes Maths AA', 'https://www.blitznotes.org', 'Student-made AA-focused notes', 'Mathematics AA HL', 'Free', 3, FALSE, '2025-09-01', 'approved'),
  ('aimnova-maths-aa-hl-notes-mathematics-aa-hl', 'Aimnova Maths AA HL Notes', 'https://www.aimnova.app/ib-math-aa/notes-hl', 'HL-only calculus, complex numbers, vectors coverage', 'Mathematics AA HL', 'Free', 4, TRUE, '2025-09-30', 'approved'),
  ('tutopiya-maths-aa-hl-mathematics-aa-hl', 'Tutopiya Maths AA HL', 'https://www.tutopiya.com/learning-portal/resource/ib-dp/mathematics/aa-hl/aa', 'Notes, video, AI-marked quizzes', 'Mathematics AA HL', 'Freemium', 4, FALSE, '2025-09-13', 'approved'),
  ('ibtuition-sg-cheatsheets-mathematics-aa-hl', 'ibtuition.sg Cheatsheets', 'https://ibtuition.sg/resources/', '70 hand-built topic cheatsheets', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-21', 'approved'),
  ('desmos-mathematics-aa-hl', 'Desmos', 'https://www.desmos.com', 'Free graphing calculator for functions and Paper 3', 'Mathematics AA HL', 'Free', 5, FALSE, '2025-09-16', 'approved'),
  ('geogebra-mathematics-aa-hl', 'GeoGebra', 'https://www.geogebra.org', 'Geometry/algebra visualizer for IA graphs', 'Mathematics AA HL', 'Free', 5, FALSE, '2025-09-03', 'approved'),
  ('knowt-maths-aa-hl-mathematics-aa-hl', 'Knowt Maths AA HL', 'https://knowt.com/exams/IB', 'Flashcards and AI study guides', 'Mathematics AA HL', 'Freemium', 3, FALSE, '2025-09-18', 'approved'),
  ('revision-village-youtube-mathematics-aa-hl', 'Revision Village YouTube', 'https://www.youtube.com/@revisionvillage-ibmathemat6191', 'Free video walkthroughs of AA/AI topics', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-17', 'approved'),
  ('mitch-campbell-youtube-mathematics-aa-hl', 'Mitch Campbell YouTube', 'https://www.youtube.com/@OSC1990', 'Cross-subject Maths and Physics video lessons', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-05', 'approved'),
  ('science-tutor-youtube-mathematics-aa-hl', 'Science Tutor YouTube', 'https://www.youtube.com/@theonlinesciencetutor2720', 'Cross-subject Maths and Physics video lessons', 'Mathematics AA HL', 'Free', 4, FALSE, '2025-09-26', 'approved'),
  ('3blue1brown-mathematics-aa-hl', '3Blue1Brown', 'https://www.youtube.com/@3blue1brown', 'Conceptual/visual maths intuition', 'Mathematics AA HL', 'Free', 5, FALSE, '2025-09-06', 'approved'),
  ('savemyexams-physics-hl-notes-physics-hl', 'SaveMyExams Physics HL Notes', 'https://www.savemyexams.com/dp/physics/ib/23/hl/revision-notes/', 'Concise official-style topic notes', 'Physics HL', 'Freemium', 5, FALSE, '2025-09-25', 'approved'),
  ('quizlet-physics-textbook-solutions-physics-hl', 'Quizlet Physics Textbook Solutions', 'https://quizlet.com/explanations/textbook-solutions/physics-for-the-ib-diploma-6th-edition-9781107628199', 'Full worked answers to the standard HL textbook (Tsokos 6th Ed.)', 'Physics HL', 'Free', 5, FALSE, '2025-09-08', 'approved'),
  ('mega-lecture-physics-notes-physics-hl', 'Mega Lecture Physics Notes', 'https://megalecture.com/ib-dp-physics-notes-worksheets/', 'Free 2025-syllabus PDF booklets SL and HL', 'Physics HL', 'Free', 4, FALSE, '2025-09-24', 'approved'),
  ('ibphysics-org-physics-hl', 'IBPhysics.org', 'https://www.studyib.com/ib/resources/ibphysics', 'Comprehensive SL/HL revision notes', 'Physics HL', 'Free', 4, FALSE, '2025-09-26', 'approved'),
  ('aimnova-physics-hl-notes-physics-hl', 'Aimnova Physics HL Notes', 'https://www.aimnova.app/ib-notes', 'Full topic notes including HL extensions', 'Physics HL', 'Free', 4, FALSE, '2025-09-21', 'approved'),
  ('tutopiya-physics-hl-physics-hl', 'Tutopiya Physics HL', 'https://www.tutopiya.com/study-resources/ib-dp/physics-hl/', 'Notes, AI-marked questions, past papers', 'Physics HL', 'Freemium', 4, FALSE, '2025-09-12', 'approved'),
  ('ibtuition-sg-physics-cheatsheets-physics-hl', 'ibtuition.sg Physics Cheatsheets', 'https://ibtuition.sg/resources/', '24 topic cheatsheets with GDC steps', 'Physics HL', 'Free', 4, FALSE, '2025-09-26', 'approved'),
  ('isaac-physics-physics-hl', 'Isaac Physics', 'https://isaacphysics.org', 'University-style problems for HL-depth practice', 'Physics HL', 'Free', 4, FALSE, '2025-09-27', 'approved'),
  ('hyperphysics-physics-hl', 'HyperPhysics', 'http://hyperphysics.phy-astr.gsu.edu', 'Concept maps for IA theory background', 'Physics HL', 'Free', 4, FALSE, '2025-09-21', 'approved'),
  ('phet-simulations-physics-hl', 'PhET Simulations', 'https://phet.colorado.edu', 'Free physics simulations for IA data collection', 'Physics HL', 'Free', 5, FALSE, '2025-09-22', 'approved'),
  ('chris-doner-youtube-physics-hl', 'Chris Doner YouTube', 'https://www.youtube.com/@donerphysics', 'Physics topic videos', 'Physics HL', 'Free', 4, FALSE, '2025-09-01', 'approved'),
  ('matt-anderson-youtube-physics-hl', 'Matt Anderson YouTube', 'https://www.youtube.com/@yoprofmatt', 'Physics topic videos', 'Physics HL', 'Free', 4, FALSE, '2025-09-09', 'approved'),
  ('andy-masley-youtube-physics-hl', 'Andy Masley YouTube', 'https://www.youtube.com/@AndyMasley', 'Physics SL-focused explainer videos', 'Physics HL', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('prof-varun-youtube-physics-hl', 'Prof. Varun YouTube', 'https://www.youtube.com/@profvarun', 'Physics HL/SL past-paper question walkthroughs', 'Physics HL', 'Free', 4, FALSE, '2025-09-16', 'approved'),
  ('richard-thornley-ib-chem-vids-chemistry-hl', 'Richard Thornley (IB Chem Vids)', 'https://www.youtube.com/@ibchemvids', 'Gold-standard HL/SL Chemistry video teaching', 'Chemistry HL', 'Free', 5, FALSE, '2025-09-30', 'approved'),
  ('msjchem-youtube-chemistry-hl', 'MSJChem YouTube', 'https://www.youtube.com/@MSJChem', 'Short tutorial videos and free worksheets', 'Chemistry HL', 'Free', 4, FALSE, '2025-09-05', 'approved'),
  ('elliot-brodie-youtube-chemistry-hl', 'Elliot Brodie YouTube', 'https://www.youtube.com/@elliotbrodie', 'Chemistry topic videos', 'Chemistry HL', 'Free', 4, FALSE, '2025-09-03', 'approved'),
  ('chemjungle-youtube-chemistry-hl', 'ChemJungle YouTube', 'https://www.youtube.com/@ChemJungle', 'Chemistry topic videos', 'Chemistry HL', 'Free', 4, FALSE, '2025-09-05', 'approved'),
  ('andrew-weng-youtube-playlists-chemistry-hl', 'Andrew Weng YouTube Playlists', 'https://www.youtube.com/user/theandrewvideos/playlists', 'Organized Chemistry playlists by topic', 'Chemistry HL', 'Free', 3, FALSE, '2025-09-15', 'approved'),
  ('aimnova-chemistry-hl-notes-chemistry-hl', 'Aimnova Chemistry HL Notes', 'https://www.aimnova.app/ib-chemistry/notes-hl', 'Full syllabus notes for first-exams-2025', 'Chemistry HL', 'Free', 4, FALSE, '2025-09-28', 'approved'),
  ('tutopiya-chemistry-hl-chemistry-hl', 'Tutopiya Chemistry HL', 'https://www.tutopiya.com/study-resources/ib-dp/chemistry-hl/', 'Notes, AI-marked quizzes, past papers', 'Chemistry HL', 'Freemium', 4, FALSE, '2025-09-11', 'approved'),
  ('chemlibretexts-chemistry-hl', 'ChemLibreTexts', 'https://chem.libretexts.org', 'Deep theory background for IA/EE research', 'Chemistry HL', 'Free', 4, FALSE, '2025-09-23', 'approved'),
  ('chemguide-chemistry-hl', 'ChemGuide', 'https://www.chemguide.co.uk', 'Extremely clear explanations for tricky HL topics', 'Chemistry HL', 'Free', 5, FALSE, '2025-09-01', 'approved'),
  ('phet-chemistry-sims-chemistry-hl', 'PhET Chemistry Sims', 'https://phet.colorado.edu', 'Titration and kinetics simulations for IA', 'Chemistry HL', 'Free', 5, FALSE, '2025-09-21', 'approved'),
  ('ib-chemistry-questionbank-ellesmere-chemistry-hl', 'IB Chemistry Questionbank (Ellesmere)', 'https://sites.google.com/site/ibchemistryellesmerecollege/home', 'Topic-organized SL/HL question bank', 'Chemistry HL', 'Free', 3, FALSE, '2025-09-24', 'approved'),
  ('yambilla-geography-notes-geography-sl', 'Yambilla Geography Notes', 'https://yambilla.com', 'Teacher-made notes, core plus all 7 options', 'Geography SL', 'Free', 5, FALSE, '2025-09-19', 'approved'),
  ('ibgeographynotes-com-geography-sl', 'ibgeographynotes.com', 'https://www.ibgeographynotes.com/unit-1-population-distribution', 'Unit-by-unit SL notes with vocab lists', 'Geography SL', 'Free', 5, FALSE, '2025-09-04', 'approved'),
  ('samthecamvet-notes-geography-sl', 'SamTheCamVet Notes', 'https://samthecamvet.wordpress.com/2020/07/30/free-ib-hl-sl-geography-notes/', 'Free downloadable HL/SL notes', 'Geography SL', 'Free', 4, FALSE, '2025-09-13', 'approved'),
  ('ib-geography-pods-geography-sl', 'IB Geography Pods', 'http://www.ibgeographypods.org', 'Podcast-style audio revision by topic', 'Geography SL', 'Free', 3, FALSE, '2025-09-01', 'approved'),
  ('aimnova-geography-notes-geography-sl', 'Aimnova Geography Notes', 'https://www.aimnova.app/ib-notes', 'SL/HL core plus all 7 options', 'Geography SL', 'Free', 4, FALSE, '2025-09-06', 'approved'),
  ('knowt-geography-sl-geography-sl', 'Knowt Geography SL', 'https://knowt.com/exams/IB/IB-Geography-(SL)', 'Flashcards plus unit-by-unit study guides', 'Geography SL', 'Free', 4, FALSE, '2025-09-10', 'approved'),
  ('savemyexams-geography-geography-sl', 'SaveMyExams Geography', 'https://www.savemyexams.com/dp/geography/', 'Notes plus past-paper walkthroughs', 'Geography SL', 'Freemium', 4, FALSE, '2025-09-06', 'approved'),
  ('our-world-in-data-geography-sl', 'Our World in Data', 'https://ourworldindata.org', 'Case-study statistics for essays and IA', 'Geography SL', 'Free', 5, FALSE, '2025-09-30', 'approved'),
  ('world-bank-open-data-geography-sl', 'World Bank Open Data', 'https://data.worldbank.org', 'Global datasets for Geography IA', 'Geography SL', 'Free', 5, FALSE, '2025-09-01', 'approved'),
  ('eurostat-geography-sl', 'Eurostat', 'https://ec.europa.eu/eurostat/', 'EU-specific statistics for Geography IA', 'Geography SL', 'Free', 5, FALSE, '2025-09-07', 'approved'),
  ('ibenglishguys-com-english-lang-lit-sl', 'ibenglishguys.com', 'https://ibenglishguys.com', 'Full English A guide site', 'English Lang&Lit SL', 'Free', 5, FALSE, '2025-09-09', 'approved'),
  ('ib-english-guys-youtube-english-lang-lit-sl', 'IB English Guys YouTube', 'https://www.youtube.com/channel/UCEZHU9lVH7h2p60KI-rEbDA', 'Companion video channel', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('tim-nance-nancenotes-youtube-english-lang-lit-sl', 'Tim Nance (Nancenotes) YouTube', 'https://www.youtube.com/@Nancenotes', 'English Lit/Lang analysis videos', 'English Lang&Lit SL', 'Free', 5, FALSE, '2025-09-03', 'approved'),
  ('ibyourwayout-lang-lit-sl-english-lang-lit-sl', 'ibyourwayout Lang&Lit SL', 'https://ibyourwayout.wordpress.com/english-a-language-literature-sl/', 'Structured notes and essay guidance', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('mrs-macfarland-non-literary-analysis-english-lang-lit-sl', 'Mrs. Macfarland Non-Literary Analysis', 'https://www.mrsmacfarland.com/ll/non-literary-analysis', 'Paper 1 non-literary text-type breakdowns', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-23', 'approved'),
  ('webersown-lang-lit-cheat-sheet-english-lang-lit-sl', 'Webersown Lang&Lit Cheat Sheet', 'https://webersown.weebly.com/uploads/8/9/8/6/8986793/ib-langlit-cheat-sheet_paper_1.pdf', 'Paper 1 unseen-text cheat sheet', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-11', 'approved'),
  ('blitznotes-eng-lang-lit-sl-english-lang-lit-sl', 'BlitzNotes Eng Lang&Lit SL', 'https://www.blitznotes.org/ib/eng-langlit-sl', 'Continuously updated concept notes', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-23', 'approved'),
  ('savemyexams-eng-lang-lit-sl-english-lang-lit-sl', 'SaveMyExams Eng Lang&Lit SL', 'https://www.savemyexams.com/dp/english-language-and-literature/ib/english-a-language-and-literature/19/sl/revision-notes/', 'Full revision notes', 'English Lang&Lit SL', 'Freemium', 5, FALSE, '2025-09-13', 'approved'),
  ('revisiondojo-eng-lang-lit-english-lang-lit-sl', 'RevisionDojo Eng Lang&Lit', 'https://www.revisiondojo.com/ib/ib-english-langlit-new', 'Notes, question bank, and model essays', 'English Lang&Lit SL', 'Freemium', 5, FALSE, '2025-09-30', 'approved'),
  ('aimnova-eng-lang-lit-notes-english-lang-lit-sl', 'Aimnova Eng Lang&Lit Notes', 'https://www.aimnova.app/ib-notes', 'Paper 1/2 and IO worked models', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-09', 'approved'),
  ('sparknotes-english-lang-lit-sl', 'SparkNotes', 'https://www.sparknotes.com', 'Text summaries and analysis', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-07', 'approved'),
  ('poetry-foundation-english-lang-lit-sl', 'Poetry Foundation', 'https://www.poetryfoundation.org', 'Full poem texts with critical context', 'English Lang&Lit SL', 'Free', 4, FALSE, '2025-09-16', 'approved'),
  ('aimnova-german-notes-german-lang-lit-sl', 'Aimnova German Notes', 'https://www.aimnova.app/ib-notes', 'Notes and flashcards across 5 prescribed themes', 'German Lang&Lit SL', 'Free', 4, FALSE, '2025-09-26', 'approved'),
  ('deutsche-welle-deutsch-lernen-german-lang-lit-sl', 'Deutsche Welle Deutsch Lernen', 'https://www.dw.com/de/deutsch-lernen/s-2055', 'Graded articles and audio for oral prep', 'German Lang&Lit SL', 'Free', 5, FALSE, '2025-09-27', 'approved'),
  ('goethe-institut-online-exercises-german-lang-lit-sl', 'Goethe-Institut Online Exercises', 'https://www.goethe.de/en/spr/ueb.html', 'Grammar and vocab practice by CEFR level', 'German Lang&Lit SL', 'Free', 5, FALSE, '2025-09-18', 'approved'),
  ('nachrichtenleicht-dlf-german-lang-lit-sl', 'Nachrichtenleicht (DLF)', 'https://www.nachrichtenleicht.de', 'Simplified German news for Paper 1 practice', 'German Lang&Lit SL', 'Free', 5, FALSE, '2025-09-06', 'approved'),
  ('linguee-german-lang-lit-sl', 'Linguee', 'https://www.linguee.com', 'Contextual translation dictionary for essays', 'German Lang&Lit SL', 'Free', 5, FALSE, '2025-09-08', 'approved'),
  ('duden-online-german-lang-lit-sl', 'Duden Online', 'https://www.duden.de', 'Authoritative dictionary and grammar reference', 'German Lang&Lit SL', 'Free', 5, FALSE, '2025-09-13', 'approved'),
  ('leo-dictionary-german-lang-lit-sl', 'LEO Dictionary', 'https://dict.leo.org', 'Community-verified German-English translations', 'German Lang&Lit SL', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('marxify-ia-ee-tok-exemplars-guides', 'Marxify', 'https://pirateib.sh/marxify/', 'Free IA/EE/TOK exemplar bank', 'IA / EE / TOK Exemplars & Guides', 'Free', 5, FALSE, '2025-09-21', 'approved'),
  ('pirateib-official-ee-exemplars-ia-ee-tok-exemplars-guides', 'pirateIB Official EE Exemplars', 'https://dl.pirateib.sh/IB%20OFFICIAL%20EE%20EXEMPLARS/', 'Raw folder of official IB EE exemplars', 'IA / EE / TOK Exemplars & Guides', 'Free', 5, FALSE, '2025-09-29', 'approved'),
  ('clastify-ia-ee-tok-exemplars-guides', 'Clastify', 'https://www.clastify.com', 'Examiner-reviewed exemplars, IA/EE/TOK/RQ guides', 'IA / EE / TOK Exemplars & Guides', 'Freemium', 5, FALSE, '2025-09-28', 'approved'),
  ('tok-skills-for-success-pdf-ia-ee-tok-exemplars-guides', 'TOK Skills for Success PDF', 'https://drive.google.com/file/d/1sLO9OPbNMXwycqHR8wV9gC64WqRNomA0/view', 'Full TOK textbook PDF by John Sprague', 'IA / EE / TOK Exemplars & Guides', 'Free', 5, FALSE, '2025-09-17', 'approved'),
  ('cloudscore-ia-ee-tok-exemplars-guides', 'Cloudscore', 'https://www.thecloudscore.com', 'Video tutorials and exemplar papers', 'IA / EE / TOK Exemplars & Guides', 'Freemium', 3, FALSE, '2025-09-23', 'approved'),
  ('examdojo-ai-study-tools', 'ExamDojo', 'https://app.examdojo.com', 'AI-marked practice questions, subject-mapped', 'AI Study Tools', 'Freemium', 4, TRUE, '2025-09-28', 'approved'),
  ('cognity-ai-study-tools', 'Kognity', 'https://app.kognity.com', 'AI tutoring with adaptive question sets', 'AI Study Tools', 'Freemium', 4, FALSE, '2025-09-26', 'approved'),
  ('perplexity-ai-study-tools', 'Perplexity', 'https://www.perplexity.ai', 'Research assistant for EE/IA source-checking', 'AI Study Tools', 'Freemium', 5, FALSE, '2025-09-23', 'approved'),
  ('aimnova-ai-study-tools', 'Aimnova', 'https://www.aimnova.app', 'Free AI-aligned notes across most DP subjects', 'AI Study Tools', 'Free', 5, TRUE, '2025-09-29', 'approved'),
  ('tutopiya-ai-study-tools', 'Tutopiya', 'https://www.tutopiya.com', 'AI-marked quizzes, notes, grade predictor', 'AI Study Tools', 'Freemium', 4, FALSE, '2025-09-30', 'approved'),
  ('knowt-ai-study-tools', 'Knowt', 'https://knowt.com', 'AI flashcard and study-guide generator', 'AI Study Tools', 'Freemium', 4, FALSE, '2025-09-09', 'approved'),
  ('notebooklm-ai-study-tools', 'NotebookLM', 'https://notebooklm.google.com', 'Upload PDFs for AI Q&A and audio summaries', 'AI Study Tools', 'Free', 5, TRUE, '2025-09-30', 'approved'),
  ('grammarly-ai-study-tools', 'Grammarly', 'https://www.grammarly.com', 'Grammar and clarity checker for EE/IA/TOK drafts', 'AI Study Tools', 'Freemium', 4, FALSE, '2025-09-03', 'approved'),
  ('quillbot-ai-study-tools', 'QuillBot', 'https://quillbot.com', 'Paraphrasing and citation generator', 'AI Study Tools', 'Freemium', 3, FALSE, '2025-09-01', 'approved'),
  ('ibpredict-org-grade-score-calculators', 'IBPredict.org', 'https://ibpredict.org', 'Predicted score calculator with session/timezone selector', 'Grade & Score Calculators', 'Free', 5, FALSE, '2025-09-16', 'approved'),
  ('ib45-github-grade-score-calculators', 'IB45 (GitHub)', 'https://github.com/AppleEpic101/IB45', 'Open-source predicted-score tool with probability graphs', 'Grade & Score Calculators', 'Free', 4, FALSE, '2025-09-09', 'approved'),
  ('ibcalculator-com-grade-score-calculators', 'IBcalculator.com', 'https://www.ibcalculator.com', 'Grade calculator using official boundaries 2019-present', 'Grade & Score Calculators', 'Free', 4, FALSE, '2025-09-01', 'approved'),
  ('ibcalc-com-grade-score-calculators', 'ibcalc.com', 'https://www.ibcalc.com', 'Score calculator with AI university-advice add-on', 'Grade & Score Calculators', 'Free', 4, FALSE, '2025-09-16', 'approved'),
  ('clastify-grade-calculators-grade-score-calculators', 'Clastify Grade Calculators', 'https://www.clastify.com/ib-grade-calculator/tok', 'Per-subject estimator using historical boundaries', 'Grade & Score Calculators', 'Free', 4, FALSE, '2025-09-02', 'approved'),
  ('tutopiya-grade-predictor-grade-score-calculators', 'Tutopiya Grade Predictor', 'https://www.tutopiya.com/tools/grade-predictor/', 'Per-paper mark entry to predicted grade', 'Grade & Score Calculators', 'Free', 4, FALSE, '2025-09-20', 'approved'),
  ('knowt-flashcards-active-recall', 'Knowt', 'https://knowt.com', 'Millions of flashcard sets and AI study guides', 'Flashcards & Active Recall', 'Freemium', 5, FALSE, '2025-09-27', 'approved'),
  ('anki-flashcards-active-recall', 'Anki', 'https://apps.ankiweb.net', 'Spaced-repetition flashcards with shared IB decks', 'Flashcards & Active Recall', 'Free', 5, FALSE, '2025-09-13', 'approved'),
  ('quizlet-flashcards-active-recall', 'Quizlet', 'https://quizlet.com', 'Flashcards, quizzes, and textbook solution sets', 'Flashcards & Active Recall', 'Freemium', 4, FALSE, '2025-09-01', 'approved'),
  ('richard-thornley-ib-chem-vids-youtube-channels', 'Richard Thornley (IB Chem Vids)', 'https://www.youtube.com/@ibchemvids', 'Chemistry video teaching', 'YouTube Channels', 'Free', 5, FALSE, '2025-09-10', 'approved'),
  ('msjchem-youtube-channels', 'MSJChem', 'https://www.youtube.com/@MSJChem', 'Chemistry tutorials', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-24', 'approved'),
  ('elliot-brodie-youtube-channels', 'Elliot Brodie', 'https://www.youtube.com/@elliotbrodie', 'Chemistry videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-22', 'approved'),
  ('chemjungle-youtube-channels', 'ChemJungle', 'https://www.youtube.com/@ChemJungle', 'Chemistry videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-06', 'approved'),
  ('chris-doner-youtube-channels', 'Chris Doner', 'https://www.youtube.com/@donerphysics', 'Physics videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-07', 'approved'),
  ('matt-anderson-youtube-channels', 'Matt Anderson', 'https://www.youtube.com/@yoprofmatt', 'Physics videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-14', 'approved'),
  ('andy-masley-youtube-channels', 'Andy Masley', 'https://www.youtube.com/@AndyMasley', 'Physics SL videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-20', 'approved'),
  ('prof-varun-youtube-channels', 'Prof. Varun', 'https://www.youtube.com/@profvarun', 'Physics walkthroughs', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-29', 'approved'),
  ('science-tutor-youtube-channels', 'Science Tutor', 'https://www.youtube.com/@theonlinesciencetutor2720', 'Maths and Physics', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-11', 'approved'),
  ('mitch-campbell-youtube-channels', 'Mitch Campbell', 'https://www.youtube.com/@OSC1990', 'Maths and Physics', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-29', 'approved'),
  ('revision-village-youtube-channels', 'Revision Village', 'https://www.youtube.com/@revisionvillage-ibmathemat6191', 'Maths videos', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-02', 'approved'),
  ('3blue1brown-youtube-channels', '3Blue1Brown', 'https://www.youtube.com/@3blue1brown', 'Maths/Physics conceptual', 'YouTube Channels', 'Free', 5, FALSE, '2025-09-27', 'approved'),
  ('tim-nance-youtube-channels', 'Tim Nance', 'https://www.youtube.com/@Nancenotes', 'English Lit/Lang', 'YouTube Channels', 'Free', 5, FALSE, '2025-09-12', 'approved'),
  ('ib-english-guys-youtube-channels', 'IB English Guys', 'https://www.youtube.com/channel/UCEZHU9lVH7h2p60KI-rEbDA', 'English A', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-15', 'approved'),
  ('crash-course-youtube-channels', 'Crash Course', 'https://www.youtube.com/@crashcourse', 'Cross-subject primers', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-15', 'approved'),
  ('ib-like-cole-youtube-channels', 'IB Like Cole', 'https://www.youtube.com/@iblikecole9167', 'General IB tips/advice', 'YouTube Channels', 'Free', 4, FALSE, '2025-09-16', 'approved'),
  ('r-ibo-communities', 'r/IBO', 'https://www.reddit.com/r/IBO', 'Main IB subreddit with FAQ wiki and megathreads', 'Communities', 'Free', 5, FALSE, '2025-09-01', 'approved'),
  ('iblieve-org-communities', 'iblieve.org', 'https://iblieve.org', 'General IB community hub', 'Communities', 'Free', 3, FALSE, '2025-09-08', 'approved'),
  ('pirateib-telegram-communities', 'pirateIB Telegram', 'https://telegram.pirateib.sh', 'Announcements and resource sharing', 'Communities', 'Free', 4, FALSE, '2025-09-03', 'approved'),
  ('pirateib-instagram-communities', 'pirateIB Instagram', 'https://instagram.pirateib.sh', 'Announcements and resource sharing', 'Communities', 'Free', 3, FALSE, '2025-09-10', 'approved'),
  ('anna-s-archive-document-paywall-access', 'Anna''s Archive', 'https://annas-archive.org', 'Book and paper mirror aggregator', 'Document & Paywall Access', 'Free', 4, FALSE, '2025-09-01', 'approved'),
  ('libgen-document-paywall-access', 'LibGen', 'https://libgen.bz', 'Textbook and ebook mirror', 'Document & Paywall Access', 'Free', 4, FALSE, '2025-09-28', 'approved'),
  ('sci-hub-document-paywall-access', 'Sci-Hub', 'https://sci-hub.ru', 'Academic paper access for EE citations', 'Document & Paywall Access', 'Free', 3, FALSE, '2025-09-05', 'approved'),
  ('scribd-downloader-document-paywall-access', 'Scribd Downloader', 'https://scribd.vdownloaders.com', 'Unlock Scribd documents', 'Document & Paywall Access', 'Free', 3, FALSE, '2025-09-29', 'approved'),
  ('studocu-downloader-document-paywall-access', 'Studocu Downloader', 'https://www.downstudocu.net', 'Unlock Studocu documents', 'Document & Paywall Access', 'Free', 3, FALSE, '2025-09-13', 'approved'),
  ('issuu-downloader-document-paywall-access', 'Issuu Downloader', 'https://issuu-downloader.com', 'Unlock Issuu documents', 'Document & Paywall Access', 'Free', 3, FALSE, '2025-09-26', 'approved'),
  ('pirateib-textbooks-folder-textbooks-ebooks', 'pirateIB Textbooks folder', 'https://dl.pirateib.sh', 'Full IB-authorized textbook PDFs, all groups', 'Textbooks & eBooks', 'Free', 5, FALSE, '2025-09-26', 'approved'),
  ('scienceknowledge-ib-textbooks-textbooks-ebooks', 'ScienceKnowledge IB Textbooks', 'https://scienceknowledge.webador.com/ib-textbooks', 'Physics/Chemistry coursebook PDFs', 'Textbooks & eBooks', 'Free', 4, FALSE, '2025-09-28', 'approved'),
  ('chemistry-com-pk-textbooks-ebooks', 'chemistry.com.pk', 'https://chemistry.com.pk/books/chemistry-for-the-ib-diploma-2e-christopher-talbot/', 'Chemistry for the IB Diploma free download', 'Textbooks & eBooks', 'Free', 4, FALSE, '2025-09-28', 'approved'),
  ('official-textbook-list-pdf-textbooks-ebooks', 'Official Textbook List PDF', 'https://isob.ukw.edu.pl/wp-content/uploads/2021/06/textbooks-for-the-ib-diploma-programme-2021-2023.pdf', 'Official ISBN/edition reference across subjects', 'Textbooks & eBooks', 'Free', 4, FALSE, '2025-09-28', 'approved'),
  ('google-scholar-databases-research', 'Google Scholar', 'https://scholar.google.com', 'Peer-reviewed sources for EE/IA citations', 'Databases & Research', 'Free', 5, FALSE, '2025-09-13', 'approved'),
  ('zotero-databases-research', 'Zotero', 'https://www.zotero.org', 'Free citation manager for EE bibliography', 'Databases & Research', 'Free', 5, FALSE, '2025-09-06', 'approved'),
  ('mybib-databases-research', 'MyBib', 'https://www.mybib.com', 'Citation generator for all referencing styles', 'Databases & Research', 'Free', 5, FALSE, '2025-09-17', 'approved'),
  ('scribbr-citation-generator-databases-research', 'Scribbr Citation Generator', 'https://www.scribbr.com/citation/generator/cite/', 'Alternative citation generator', 'Databases & Research', 'Free', 4, FALSE, '2025-09-05', 'approved'),
  ('edx-university-application-prep', 'edX', 'https://www.edx.org', 'Free university-level courses with certificates', 'University Application & Prep', 'Freemium', 5, FALSE, '2025-09-15', 'approved'),
  ('common-app-university-application-prep', 'Common App', 'https://www.commonapp.org', 'US university applications', 'University Application & Prep', 'Free', 5, FALSE, '2025-09-10', 'approved'),
  ('ucas-university-application-prep', 'UCAS', 'https://www.ucas.com', 'UK university applications', 'University Application & Prep', 'Free', 5, FALSE, '2025-09-18', 'approved'),
  ('college-confidential-university-application-prep', 'College Confidential', 'https://www.collegeconfidential.com', 'US-focused student Q&A community', 'University Application & Prep', 'Free', 4, FALSE, '2025-09-25', 'approved'),
  ('the-student-room-university-application-prep', 'The Student Room', 'https://www.thestudentroom.co.uk', 'UK-focused student Q&A community', 'University Application & Prep', 'Free', 4, FALSE, '2025-09-06', 'approved')
ON CONFLICT (id) DO NOTHING;